### ISSUE TITLE
unclosed file discriptor problem

### ISSUE THREAD

**Issue by ayoubelmohamedi** [VICTORxEVO/minishell#9]
Eurika ✨➜ ls | g 
Eureka: g: command not found !
==1027279== 
==1027279== FILE DESCRIPTORS: 3 open (1 std) at exit.
==1027279== Open file descriptor 4:
==1027279==    at 0x49DA07D: pipe (pipe.c:29)
==1027279==    by 0x403CC4: exec_ncmd (execution.c:25)
==1027279==    by 0x403FC1: execution (execution.c:96)
==1027279==    by 0x40927F: main (minishell.c:15)
==1027279== 
==1027279== Open file descriptor 3:
==1027279==    at 0x49DA07D: pipe (pipe.c:29)
==1027279==    by 0x403CC4: exec_ncmd (execution.c:25)
==1027279==    by 0x403FC1: execution (execution.c:96)
==1027279==    by 0x40927F: main (minishell.c:15)
==1027279== 
==1027279==

**Comment by VICTORxEVO** [comment]
fixed 100%
